site_name: Documentation
site_description: |
  The documentation for NOMAD plugin nomad-material-processing.
site_author: The NOMAD Authors
repo_url: https://github.com/FAIRmat-NFDI/nomad-material-processing
edit_uri: ""

nav:
  - Home: index.md
  - Explanation:
    - Levels of Schema: explanation/levelsofschema.md
    - Schemas: explanation/schemas.md
  - How-To Guides:
    - Install this Plugin: how_to/install.md
    - Use this Plugin: how_to/use_this_plugin.md
    - Contribute to this Plugin: how_to/develop.md
  - Reference: 
    - Glossary: reference/references.md
    - Schemas: 
      - reference/schemas/general.md
      - reference/schemas/combinatorial.md
      - reference/schemas/epitaxy.md
      - reference/schemas/crystal_growth.md
      - Solution:
        - reference/schemas/solution/general.md
      - Vapor Deposition:
        - reference/schemas/vapor_deposition/general.md
        - CVD:
          - reference/schemas/vapor_deposition/cvd/general.md
          - reference/schemas/vapor_deposition/cvd/movpe.md
        - PVD:
          - reference/schemas/vapor_deposition/pvd/general.md
          - reference/schemas/vapor_deposition/pvd/sputtering.md
          - reference/schemas/vapor_deposition/pvd/thermal.md
          - reference/schemas/vapor_deposition/pvd/pld.md
          - reference/schemas/vapor_deposition/pvd/mbe.md
  - Tutorials: tutorial/tutorial.md
  - Contact: contact.md
plugins:
 - search
 - macros:
    module_name: docs/main
theme:
  name: material
  palette:
    primary: '#2A4CDF'
    accent: '#008A67'
  font:
    text: 'Titillium Web'
  logo: assets/nomad-plugin-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
  custom_dir: docs/theme
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - mkdocs-click
  - pymdownx.extra
extra:
  generator: false
  homepage: https://nomad-lab.eu
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js